manifest:
  remotes:
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: 5andr0
      url-base: https://github.com/5andr0
  projects:
    - name: zmk
      remote: moergo-sc
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: 5andr0
      revision: main
  self:
    path: config
